ObsRacer.create(:name => "evan")
ObsRacer.create(:name => "Alex")
ObsRacer.create(:name => "luke")
ObsRacer.create(:name => "jon")
ObsRacer.create(:name => "evan2")
ObsRacer.create(:name => "Alex2")
ObsRacer.create(:name => "luke2")
ObsRacer.create(:name => "jon2")
ObsRacer.create(:name => "evan3")
ObsRacer.create(:name => "Alex3")
ObsRacer.create(:name => "luke3")
ObsRacer.create(:name => "jon3")
ObsRacer.create(:name => "evan4")
ObsRacer.create(:name => "Alex4")
ObsRacer.create(:name => "luke4")
ObsRacer.create(:name => "jon4")
ObsRacer.create(:name => "evan5")
ObsRacer.create(:name => "Alex5")
ObsRacer.create(:name => "luke5")
ObsRacer.create(:name => "jon5")
ObsRacer.create(:name => "evan6")
ObsRacer.create(:name => "Alex6")
ObsRacer.create(:name => "luke6")
ObsRacer.create(:name => "jon6")
ObsCategory.create(:name => "Women")
ObsCategory.create(:name => "Men")
Category.create(:name => "Women")
Category.create(:name => "Men")
t = Tournament.create(:name => "December Series")
ObsRacer.all.each{|r|
  t.tournament_participations.create(:obs_racer => r)
}
