require 'rubygems'
require 'rake'

desc 'Default: run unit tests.'
task :default => :test

require 'rake/testtask'

desc 'Run unit tests for Scribble.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.pattern = 'test/*_test.rb'
  t.verbose = true
end
